stages:
  - deps
  - lint
  - build
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  CI_JSONNET_IMAGE: docker.io/alikov/ci-jsonnet:0.2.7

version:
  stage: deps
  image: docker.io/bitnami/git:2.43.2
  script:
    - ci/scripts/version.sh ci/reports/version.env
  artifacts:
    reports:
      dotenv:
        - ci/reports/version.env
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
      variables:
        IS_TAGGED_RELEASE: "1"
    - when: on_success

deps:
  stage: deps
  image: $CI_JSONNET_IMAGE
  script:
    - jb install
  cache:
    - key:
        files:
          - jsonnetfile.lock.json
      paths:
        - vendor
  artifacts:
    paths:
      - vendor
    expire_in: 1 day

check-style:
  stage: lint
  image: $CI_JSONNET_IMAGE
  script:
    - jsonnetfmt --test *.libsonnet
    - jsonnetfmt --test *.jsonnet
  needs: []

build:
  stage: build
  image: $CI_JSONNET_IMAGE
  script:
    - jsonnet -J vendor telegraf-system.jsonnet >"ci/build/telegraf-system-${VERSION_SEMVER}.json"
  artifacts:
    paths:
      - build
    expire_in: 1 day


publish-github:
  stage: publish
  image: docker.io/python:3.12-slim
  script:
    - ci/scripts/publish-github-assets.py "ci/build/telegraf-system-${VERSION_SEMVER}.json"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
      variables:
        IS_TAGGED_RELEASE: "true"
